elgatito/plugin.video.elementum

resources/language/Croatian/strings.po

@elgatito 
There is problem with Elementum.
When is available Movies/TV Shows localized title names, Elementum will not search/play Movies/TV Shows.

Update croatian language

---

resources/language/Spanish (Argentina)/strings.po

Add spanish as spoken in Argentina (es_AR) translation.

---

addon.xml

Python reuse improves performance. I've tested and Elementum seems to have no problems with it enabled.
See https://github.com/xbmc/xbmc/pull/14136
Improve performance on Kodi 18+
Used Elementum with this enabled for a few weeks, haven't seen any differences or problems.
n/a

Enable python reuse

---

resources/language/Spanish (Argentina)/strings.po

Translation update for es_AR

---

addon.xml
resources/language/Spanish/strings.po

Improvement for translation into Spanish language of Spain

---

resources/language/Spanish/strings.po

Add new strings and fix bug translation

---

resources/language/Spanish (Argentina)/strings.po

update es_AR translation.

---

resources/language/Spanish/strings.po

Update spanish strings.po

---

resources/language/Russian/strings.po

Add some missing Russian translation

---

resources/language/Russian/strings.po
resources/language/Spanish/strings.po

Update es_ES translation

---

resources/settings.xml

Extend maximum results per page to 50

Extend maximum results per page to 50

---

resources/site-packages/elementum/dialog_select.py

in Kodi 19 function setIconImage return nop

use setArt

---

resources/language/Spanish/strings.po

Translation update for spanish [es_ES]

---

resources/language/Italian/strings.po

Updated Italian language

---

resources/language/Spanish (Argentina)/strings.po

Update es-AR translation.

---

.gitlab-ci.yml

checkout .gitlab-ci.yml

---

resources/language/Spanish (Argentina)/strings.po

Update es_AR translation

---

resources/language/Italian/strings.po

Grammar and ortography corrections

---

resources/site-packages/elementum/daemon.py
resources/site-packages/elementum/util.py

At matrix all elementum messages was printed as bytes array

Fixed logging output for elementum messages

---

resources/site-packages/elementum/monitor.py

fixed python 3 compatibility at monitor.py

---

resources/site-packages/elementum/daemon.py
resources/site-packages/elementum/overlay.py
resources/site-packages/elementum/rpc.py
resources/site-packages/elementum/util.py

Matrix compatibility updated

---

resources/language/Spanish (Argentina)/strings.po

es_AR translations update

---

resources/site-packages/elementum/monitor.py

without decode() py3 will pass string as `b'string'`
so it will lead to errors with decoding on golang side
```
2021-03-05 14:45:26.929 T:768724 WARNING <general>: [plugin.video.elementum] DEBU  main         ▶ Notification     Got notification from xbmc/VideoLibrary.OnUpdate:  ; b'eyJpdGVtIjp7ImlkIjoxMDQ1LCJ0eXBlIjoiZXBpc29kZSJ9LCJwbGF5Y291bnQiOjF9'
2021-03-05 14:45:26.929 T:768724 WARNING <general>: [plugin.video.elementum] ERRO  main         ▶ Notification     VideoLibrary.OnUpdate unexpected end of JSON input
```

fix onNotification base64 encoding for python 3

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
scripts/xgettext_remove_old_messages.sh

Remove old messages and remove them from translations
to make code cleaner and to ease work for translators
tested on kodi 19 with ru lang

Remove old messages

---

resources/language/English/strings.po
resources/language/Russian/strings.po
resources/language/messages.pot
resources/settings.xml

depends on https://github.com/elgatito/elementum/pull/34

add disable_lsd option

---

resources/site-packages/elementum/navigation.py

missing piece for https://github.com/elgatito/plugin.video.elementum/pull/721

use fanart.jpg in navigation.py

---

resources/site-packages/elementum/rpc.py

initially was used for assign torrent func. but still nice to have it for future.

add Dialog_Browse_Single

---

resources/language/English/strings.po
resources/language/Russian/strings.po
resources/language/messages.pot
resources/settings.xml

should fix https://github.com/elgatito/plugin.video.elementum/issues/743

Option to Show Episodes On Release Day

---

resources/language/English/strings.po
resources/language/Russian/strings.po
resources/language/messages.pot
resources/settings.xml

tl;dr - elementum storage=files + all extra trackers = CloseSession takes sometimes up to 120 seconds to complete => kodi hangs on exit.
оказалось, что это из-за большого кол-ва трекеров которые добавляет elementum.
для memory storage это не важно, а вот для files storage вызывает зависание при выходе даже на 2х торрентах на моём тестовом linux ПК.
сделал опцией, по умолчанию всё останется как и было.
depends on https://github.com/elgatito/elementum/pull/36
connected to https://github.com/elgatito/plugin.video.elementum/issues/733

Add settings to control adding of extra trackers and remove original trackers

---

resources/settings.xml

https://github.com/elgatito/elementum/pull/50

hide seed limits if seed_forever is set

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
scripts/xgettext_remove_old_messages.sh

Add new po messages, delete old.
+update cleanup script.

Add new po messages, delete old

---

resources/site-packages/elementum/daemon.py

depends on https://github.com/elgatito/elementum/pull/54
fix #761

run elementum with args

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

Update reference values for messages in messages.pot
fixes https://github.com/elgatito/plugin.video.elementum/issues/725
after we agree about changes i will update `msgid` in all translations.

Update reference values for messages in messages.pot

---

resources/language/English/strings.po
resources/language/Russian/strings.po
resources/language/messages.pot
resources/settings.xml

мерж функциональности из https://github.com/elgatito/elementum/pull/39
хотел смигрировать старые торренты из старого smpc в новый kodi и понял, что ещё было бы неплохо очистить трекеры, но не теряя статистику.
ну и в принципе, лучше когда есть выбор когда именно мы изменяем трекеры.
зависит от
https://github.com/elgatito/elementum/pull/59

add modify_trackers_strategy

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/site-packages/elementum/rpc.py

for https://github.com/elgatito/plugin.video.elementum/issues/748
depends on https://github.com/elgatito/elementum/pull/63
also provides [`ToggleWatched`](https://kodi.wiki/view/Keymap#Actions) func.

Add Mark as watched in Trakt menu item

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

for https://github.com/elgatito/elementum/pull/60

add ability to re-add deleted video

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

https://github.com/elgatito/plugin.video.elementum/issues/684#issuecomment-845279230
for https://github.com/elgatito/plugin.video.elementum/issues/684

tmdb_show_use_prod_company_as_studio

---

scripts/xgettext_get_available_ids.sh

script to get available ids for resources/language/messages.pot

add scripts/xgettext_get_available_ids.sh

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

"Show number of unwatched episodes in Shows/Seasons" option
depends on https://github.com/elgatito/elementum/pull/67

Show number of unwatched episodes in Shows/Seasons

---

resources/site-packages/elementum/navigation.py

fixes https://github.com/elgatito/plugin.video.elementum/issues/783
depends on https://github.com/elgatito/elementum/pull/70

add UniqueIDs to generated ListItem

---

resources/site-packages/elementum/navigation.py

as a intermediate step for https://github.com/elgatito/plugin.video.elementum/issues/738
depends on https://github.com/elgatito/elementum/pull/68

More artwork images

---

resources/settings.xml

also it takes a lot of time to open very big user list  - so i think we should turn it off by default.
e.g. https://trakt.tv/users/justin/lists/trakt-popular-tv-shows?sort=rank,asc with 250 shows

fix typo in show_unwatched_episodes_number and disable it by default

---

resources/site-packages/elementum/navigation.py

fix https://github.com/elgatito/plugin.video.elementum/issues/793

remove extra labels before setInfo

---

resources/settings.xml

now show_unwatched_episodes_number is fast (if tmdb is used, which is default)
depends on https://github.com/elgatito/elementum/pull/72

re-enable show_unwatched_episodes_number

---

resources/site-packages/elementum/navigation.py

remove properties in getInfoLabels

---

README.md

https://github.com/elgatito/plugin.video.elementum/issues/806
https://github.com/elgatito/plugin.video.elementum/issues/576

note about android 4.4

---

resources/skins/Default/720p/DialogInsert.xml
resources/skins/Default/720p/DialogSelectLarge.xml

Fixing some visual bugs and skin polishing. There were also problems with displaying some buttons in custom skins.

Update elementum skin

---

resources/skins/Default/720p/DialogSelectLarge.xml

Just a small improvement in visibility on darker skins.

Visibility improvement

---

resources/language/French/strings.po

Updated missing or wrong translations for French language
Improve translations
Local DEV machine

Translation update for French

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/site-packages/elementum/navigation.py

перевод для `"Use fallback fanart if fanart wasn't found"` не очень был - я и сам время от времени и забываю, что это значит, а на англ всё сразу ясно. к тому же я англ текст и менял 3 года назад чтобы сделать его яснее, но почему-то забыл поменять перевод.
для украинского кстати такая же беда, если верить онлайн переводчику.
E721 от линтера https://docs.astral.sh/ruff/rules/type-comparison/
и ещё несколько исправлений названий, для ясности того, что они значат.
E721 проверил на python 2 и 3.
Перевод проверил визуально, у меня даже вмещается без перемотки.

Minor fixes

---

resources/language/Ukrainian/strings.po

found this by running `scripts/xgettext_merge.sh`

Fix typo in Ukrainian/strings.po

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

Add msgid "ID of selected userlist for ...". It used to be hardcoded in settings.
We use that ID (instead of name) in golang part of code. See https://github.com/search?q=repo%3Aelgatito%2Felementum+TraktSyncRemovedMoviesList+TraktSyncRemovedShowsList+TraktSyncAddedShowsList+TraktSyncAddedMoviesList&type=code
re-work of https://github.com/elgatito/plugin.video.elementum/pull/970
if userlist is not set to anything (then ID is 0):
if userlist is set to my list called "test" (thus ID has value):

Add msgid "ID of selected userlist for ..."

---

bundle.sh
release.sh

1. PLATFORM was used instead of TARGET in bundle.sh so script tried to create zip in `/`.
2. if use TARGET - also make path absolute, b/c later scripts uses `cd ..` (thus zip was failing to find directory)
3. `platform_detect` library was missing, thus resulting addon did not work

Several fixes for bundle.sh

---

resources/site-packages/elementum/daemon.py

because temp/elementum will be deleted right after we created log file.
it used to be in `temp/elementum`
https://github.com/elgatito/plugin.video.elementum/blob/31ca42ff1826b5a34e7645172192e68a0ac8a7e5/resources/site-packages/elementum/daemon.py#L329
but then we delete this directory
https://github.com/elgatito/elementum/blob/a32c2fd51eefd8dacc2b1f7da8d77ec126df2741/config/config.go#L433
so i propose to use just temp directory for log file.
#962

put elementum.log into temp instead of temp/elementum

---

resources/language/Russian/strings.po

было то "серии", то "эпизоды" - пусть будет везде "серии", это звучит как-то более правильно.

Unify RU translation of word episode

---

resources/settings.xml

Move use_original_title to Appearance tab.
for https://github.com/elgatito/plugin.video.elementum/issues/991
depends on https://github.com/elgatito/elementum/pull/113

use_original_title only for Appearance, not for search via providers

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

So if user use TMDB as data source (default) - user still can get more precise air date from Trakt.
depends on https://github.com/elgatito/elementum/pull/119

Trakt: "Use earliest release date for progress and calendars" option

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

to avoid confusion during translations.
for https://github.com/elgatito/plugin.video.elementum/issues/1013

rename "#30477" from "Original" to "Original language"

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

max ~70 characters, 2 lines max. anything bigger that that is not visible. in all skins as i can see.
example:

Make sure that all messages in settings have correct new line position.

---

README.md

Fix gitlab pipeline link code.
right now it has extra `[` that remained after removing previous link, and link leads to nowhere (generated image URL).

Fix gitlab pipeline link code in README.md

---

resources/settings.xml

Show memory-related settings only for memory storage.
before
after

Show memory-related settings only for memory storage

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

for https://github.com/elgatito/plugin.video.elementum/issues/1009

use_original_title was replaced by language & second_language

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

- Add `internal_proxy_help` to make things more clear
- Add "enable" condition for internal DNS/Proxy settings
- Update opennic dns servers as of 27.04.2024
---
@elgatito 
Should `internal_proxy_enabled` be **true** by default? [Related setting is true in burst](https://github.com/elgatito/script.elementum.burst/blob/008b53cf5d781b9292655ba224e30758b158b7be/resources/settings.xml#L5C32-L5C51).
(burst also checks if it is really enabled in elementum  https://github.com/elgatito/script.elementum.burst/blob/008b53cf5d781b9292655ba224e30758b158b7be/burst/client.py#L181 but anyway)
I am not sure about what is the best value for this setting by default.

Add internal_proxy_help, add "enable" condition for internal DNS/Proxy settings

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

for https://github.com/elgatito/plugin.video.elementum/issues/952

Make 30702 message more clear.

---

resources/site-packages/elementum/daemon.py

словил старынный баг, к сожалению не сохранил бинарь с странной чексуммой внутри, но видимо там как-то был null.
```
error <general>:   File "/home/user/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 219, in get_elementum_binary
error <general>: log.info(
...
error <general>: self.emit(record)
error <general>:   File "/home/user/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/logger.py", line 19, in emit
error <general>: xbmc.log(self.format(record), xbmc_level)
error <general>: ValueError
error <general>: embedded null character
```
т.е. exception не срабатывал внутри из-за return. а потом уже ломал логгинг в get_elementum_binary.
после фикса всё норм
```
warning <general>: [plugin.video.elementum] exception reading checksum …
```

Fix "embedded null character" exception while reading checksum

---

whatsnew.txt

Update whatsnew.txt for 0.1.103

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

to be merged after https://github.com/elgatito/elementum/pull/131

Update bittorent 'user agent' names.

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/site-packages/elementum/daemon.py

localization message for https://github.com/elgatito/elementum/pull/139

Add bittorrent ports to status page.

---

whatsnew.txt

A long time without release :-)
So I prepared the changelog for version 0.1.104.
I think a caught all important changes (probably even some minor changes too - feel free to delete some).
Also record for fix of https://github.com/elgatito/plugin.video.elementum/issues/950 should be added, but i do not know what was the root cause.
Thanks.

Changelog for version 0.1.104

---

whatsnew.txt

Added thanks to whatsnew.txt + spell check (i used https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker ).

Added thanks to whatsnew.txt + spell check.

---

whatsnew.txt

Add Changelog for 0.1.105
Remove duplicate change description for version 0.1.104 in whatsnew.txt

Changelog for 0.1.105

---

resources/language/Spanish/strings.po

Update spanish translation [es_ES]

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

messages for https://github.com/elgatito/elementum/pull/143

Messages for "delete torrent" confirmation

---

resources/language/Greek/strings.po

FIrst attempt, contains only 2 fixes on typos.

Update Greek strings.po

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot
resources/settings.xml

Remove unused library_auto_scan option.
Its usage was deleted in https://github.com/elgatito/elementum/commit/6cb26121d6e18e388847ef4398d1f3d9233fa4e4
also 
```
msgctxt "#30480"
msgid "Run Kodi library update after add/delete"
```
was incorrectly translated (or used old translation) to russian, i updated translation, maybe you can update ukranian translation as well.
https://github.com/elgatito/elementum/pull/146

Remove unused library_auto_scan option.

---

resources/language/Ukrainian/strings.po
whatsnew.txt

* Update whatsnew.txt for 0.1.107: described more changes and added credits for translations.
* Update message 30480 Ukrainian translation: I used machine translation, but reverse translation looks correct, so I guess translation itself is also correct. Now all 30480 translations look correct. https://github.com/elgatito/plugin.video.elementum/pull/1088#issuecomment-2676149810

Update whatsnew 0.1.107

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

Re-check be convenient after migration to new device, for example.
for https://github.com/elgatito/elementum/pull/156

Add "Re-check torrent's data" message.

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

to be more clear.  needed for future.

Change 30412 to "Do not start binary (client mode)"

---

resources/site-packages/elementum/daemon.py

Do not fail if system does not support ctypes python module, like Xbox.
On xbox it fails with `Could not find module 'kernel32' (or one of its dependencies). Try using the full path with constructor syntax.`
With this fix at least elementum can be used as client.
Also, for xbox user should change the port for plugin.video.elementum and repository.elementumorg because:
>Universal Windows Platform (UWP) apps on Xbox One devices are restricted from binding to ports in the range [57344, 65535], inclusive.
https://learn.microsoft.com/en-us/previous-versions/windows/uwp/xbox-apps/known-issues#blocked-networking-ports-on-xbox-one
and we use ports from this range by default.

Do not fail if system does not support ctypes python module, like Xbox.

---

resources/site-packages/elementum/provider.py

Support elementum's login and password in provider so provider will not fail if user enable auth in elementum.
fixes https://github.com/elgatito/script.elementum.burst/issues/452

Support elementum's login and password in provider

---

resources/language/Croatian/strings.po
resources/language/Dutch/strings.po
resources/language/English/strings.po
resources/language/Finnish/strings.po
resources/language/French/strings.po
resources/language/German/strings.po
resources/language/Greek/strings.po
resources/language/Hebrew/strings.po
resources/language/Hungarian/strings.po
resources/language/Italian/strings.po
resources/language/Portuguese (Brazil)/strings.po
resources/language/Portuguese/strings.po
resources/language/Romanian/strings.po
resources/language/Russian/strings.po
resources/language/Slovak/strings.po
resources/language/Spanish (Argentina)/strings.po
resources/language/Spanish (Mexico)/strings.po
resources/language/Spanish/strings.po
resources/language/Swedish/strings.po
resources/language/Ukrainian/strings.po
resources/language/messages.pot

Use "addon" instead of "plugin" in messages, for consistency. Long time ago there were plugins, then they were renamed to addons. So new messages use "addon" word, old - "plugin".

Use "addon" instead of "plugin" in messages.

---

Makefile

Final fix for platform_detect

---

README.md
whatsnew.txt

то что я добавил в whatsnew.txt можно при желании подрезать, там в основном мелкие изменения, можно их и не указывать.
в README.md добавил про докер, кстати судя по логу из https://github.com/elgatito/plugin.video.elementum/issues/1111 elementum запускается на arm64 macOS с Kodi x64, тоже указал это.

Update README.md and whatsnew.txt

---

whatsnew.txt

Update whatsnew.txt for 0.1.110

Update whatsnew.txt for 0.1.110

---

scripts/changelog.sh

At least for internal usage. Convenient script.
@elgatito could you please remove wrong 0.0.48 0.0.49 0.0.50 tag so changelog.sh will work properly?

Add scripts/changelog.sh

---

.gitattributes
release.sh
scripts/changelog.sh

Update scripts/changelog.sh to be more generic. Update release.sh and .gitattributes.

Update changelog.sh release.sh .gitattributes
